const classicTruth =
[
        "What Is Your Biggest Fear About Relationships?",
        "Will You Allow Me To Check The Browsing History On Your Mobile?",
        "What Is One Thing That Would Cause Our Relationship To Break Up?",
        "Have You Ever Dated Someone Older Than You?",
        "How Many Kids Are You Planning To Have?",
        "When You Are In An Argument With Someone     Do You Apologize First To Stop The Argument?", 
        "Did You Ever Have A Tinder Profile?"  ,
        "Have You Ever Text Messaged Me While In The Shower?",     
        "How Often Do You Clear Your Browsing History?" ,     
        "Did Your Parents Ever Catch You Drinking Or Smoking?",     
        "Did you use any dating app?",
        "Do You Prefer Teenage Or Adulthood?" ,
        "How many members are there in your family",
        "Did You Ever Taste Your Pet’s Food?",
        "Have You Ever Practiced Kissing In A Mirror?",   
        "Have you Ever lied your partner?" ,  
        "Beaches or Mountains" ,
        "Who is hotter? Me or you?"  ,
        "How many ex do you have?"     , 
        "When was your first kiss?"   ,
        "Have you ever peed yourself?",  
        "Who was your worst kiss ever?",  
        "Have you ever cheated on someone?",
        "What's a bad habit you have?",  
        "When was the last time you cried?", 
        "What is your most confident about yourself?",
        "What is your biggest fear?",   
        "Who is the person you searched in your Instagram?",    
        "Did you hava a toxic relationship?",       
        "What kind of kiss do you like?"
]
const adultTruth =
[
        "How many people have you kissed?",  
        "Let someone go through your YouTube history and read it out to the group",   
        "What's your favorite body part?",  
        "Have you ever thought about the same sex?",
        "Do you prefer one-on-one or the more the merrier?",
        "Where is your favorite spot to be kissed?",
        "How do you feel about kissing in public?",
        "Have you ever tried to picture me naked?",   
        "What is the most toxic dream you've ever had?",
        "What was your first impression of me?", 
        "Using three words. How do you feel about me?",
        "What do you expect most out of a relationship?",
        "What would you do if I kissed you right now?", 
        "Have you ever flirted with a stranger online?",
        "Do you think lovemaking should happen anywhere     not just in a bed?", 
        "What kind of props do you like to use in the bedroom?",
        "At what age did you lose your virginity?",   
        "Where do you like to be touched?",
        "Have you ever sent someone a naughty picture?",       
        "Would you ever send me a naughty picture?",   
        "If you came home to find me waiting for you naked. what would you say?",
        "What would you want me to do to you right now if we were together?",   
        "What are you thinking about right now?",
        "Would you like to know how I feel about you?",
        "Say we have 20 minutes to spend together. What do we do?",
        "Do you want to see me without my shirt on?",
        "Want to exchange pics?",
        "What are you wearing right now?",
        "How many underwear do you have?",
        "If you come home stressed, what can I do to help you unwind?",
        "Can you send me a link to something sexy you would wear for me?",
        "Sleep with someone on the first date or wait for six months?",
        "Have sex in the shower or on the kitchen table?",
        "If you got to have a threesome with people in this room, who would you do it with and why?",
        "How many people have you slept with?",
        "Do you think about loving me",
        "How many times a week do yo masturbate?",
        "When did you watch adults-only videos for the first time?",
        "Name 5 parts of body you want me to kiss",
        "Do you like a lot of foreplay? What kind?",
        "Would you take a shower with me?",
        "Do you want to try to hug me",
        "Do you try to feel me up when we hug?",
        "Have you ever thought about me in the shower?",
        "Have you ever thought about me when you masturbate?",
        "what color is your underwear",
        "What's your favorite body part on a guy?",
        "Have you ever had a one-night stand?",
        "What's your favorite body part on a girl?",
        "Show the history of browser",
        "Have you ever kissed your friend",
        "Have you ever pictured me naked when talking to me?",
        "Guess the length of my penis",
        "What's an “imperfection” on my body you find sexy?",
        "What's the strangest sexy dream you've ever had?",
        "What's something about my body, you want to touch?",
        "What sex position do you prefer?",
        "Do you want to touch a sensitive part of my body?",
        "Will we be a couple?",
        "How many people have you slept with?",
        "Do you like big or small penis?",
        "What's your biggest sexual fear?",
        "In your classroom, Who you want to have sex with?",
        "What panties are you wearing?",
        "Do you think I will be a best partner"
]
const adultDare =
[
    "Give me a deep tissue massage for shoulder",
    "Put your mouth to my mouth and do anything BUT kiss",
    "Show me the last adult film you watched-no cheating!",
    "Give me a kiss on your favorite body part of mine",
    "Touch my chest",
    "Find an adult film with some moves you'd like to try and show it to me",
    "Seductively whisper in my ear the cheesiest, most awful pick up line you can think of",
    "Close your eyes and guess which body part I'm of mine about to press up against you",
    "Show one sexy picture to me",
    "Grunt to your partner",
    "Show your underwear",
    "Whisper your feeling right now",
    "Remove your bra without taking off your shirt",
    "Take a body shot",
    "Kiss them passionately, like in the movies",
    "Send the dirtiest text you can think of",
    "Show the sexiest part of your body in the least sexy way",
    "Send your sexiest selfie",
    "Watching a hot clip with your friend",
    "Hold your friend's hand 10s",
    "Kiss"                                                                                    
]
